name: app_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2
  geolocator: ^13.0.4
  flutter_map_geojson: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.3.5
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  device_info_plus: ^11.3.0
  firebase_core: ^4.0.0
  pusher_channels_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - geojson/amenity_points.geojson
    - geojson/amenity_polygons.geojson
    - geojson/landcover.geojson
    - geojson/power_line_columns.geojson
    - geojson/power_lines.geojson
    - geojson/roads.geojson
    - assets/alerta_unida_isotipo.png
    - assets/coordenadasvertical.json
    - assets/coordenadasPorterias.json
    - assets/coordenadasgrande.json
    - assets/coordenadasmediano.json
    - assets/coordenadashorizontal.json
    - assets/coordenadaspuntoreunion.json
    - assets/extintores/img.png
    - assets/Edificios/edificio_r.jpg
    - assets/Edificios/gimnasio.jpg
    - assets/Edificios/salonesy.jpg
    - assets/Edificios/almacen.jpg
    - assets/Edificios/templo.jpg
    - assets/Edificios/vinculacion.jpg
    - assets/Edificios/sistemas.jpg
    - assets/Edificios/salonest.jpg
    - assets/Edificios/salonesq.jpg
    - assets/Edificios/saloneso.jpg
    - assets/Edificios/salonesk.jpg
    - assets/Edificios/salonesi.jpg
    - assets/Edificios/salones_m.jpg
    - assets/Edificios/salones_j.jpg
    - assets/Edificios/salones_h.jpg
    - assets/Edificios/salademaestros.jpg
    - assets/Edificios/quimica.jpg
    - assets/Edificios/nite.jpg
    - assets/Edificios/mecatronica.jpg
    - assets/Edificios/laboratorioindustrialige.jpg
    - assets/Edificios/laboratorio_conta.jpg
    - assets/Edificios/laboratorio_fisica.jpg
    - assets/Edificios/laboratorio_quimica_general.jpg
    - assets/Edificios/laboratorioelectronica.jpg
    - assets/Edificios/civil.jpg
    - assets/Edificios/centrodeinformacion.jpg
    - assets/Edificios/analisis.jpg
    - assets/Edificios/cafeteria.jpg
    - assets/Edificios/ambiental.jpg
    - assets/Edificios/almacen.jpg
    - assets/Edificios/fundadores.jpg
    - assets/extintores/plantaaltay.jpg
    - assets/extintores/plantabajar.jpg
    - assets/extintores/plantabajay.jpg
    - assets/extintores/plantaaltar.jpg
    - assets/extintores/plantaaltasistemas.jpg
    - assets/extintores/plantabajasistemas.jpg
    - assets/extintores/plantabajacafeteria.jpg
    - assets/extintores/extintormaestros.jpg
    - assets/extintores/ige.jpg
    - assets/extintores/ige2.jpg
    - assets/puntosdereunion/punto2.jpg
    - assets/puntosdereunion/punto3.jpg
    - assets/puntosdereunion/puntodereunion4canchas.jpg
    - assets/puntosdereunion/puntoq.jpg
    - assets/puntosdereunion/puntoreunionmaestros.jpg
    - assets/puntosdereunion/porteriatecopias.jpg
    - assets/puntosdereunion/porteriasegunda.jpg
    - assets/puntosdereunion/porteriaenfrente.jpg
    - assets/puntosdereunion/porteriamaestros.jpg
    - assets/puntosdereunion/porteriaestudiantes.jpg



dependency_overrides:
  geolocator_android: 4.5.0
