// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXTe-_OWgUqo29ZU6xScCdndBLkF95EvM',
    appId: '1:828449012920:web:8b0f46a295ac2596eb484d',
    messagingSenderId: '828449012920',
    projectId: 'miprueba-55284',
    authDomain: 'miprueba-55284.firebaseapp.com',
    databaseURL: 'https://miprueba-55284-default-rtdb.firebaseio.com',
    storageBucket: 'miprueba-55284.firebasestorage.app',
    measurementId: 'G-RRMKLBK0N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgsFjYpBDL4u50LnckpvIjcHSyT9duW08',
    appId: '1:828449012920:android:4cc2cb0a0a9aaf46eb484d',
    messagingSenderId: '828449012920',
    projectId: 'miprueba-55284',
    databaseURL: 'https://miprueba-55284-default-rtdb.firebaseio.com',
    storageBucket: 'miprueba-55284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABSTRMNSAjubaVg0lBFCTatnTawIdhngY',
    appId: '1:828449012920:ios:b12db3d4009e595aeb484d',
    messagingSenderId: '828449012920',
    projectId: 'miprueba-55284',
    databaseURL: 'https://miprueba-55284-default-rtdb.firebaseio.com',
    storageBucket: 'miprueba-55284.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABSTRMNSAjubaVg0lBFCTatnTawIdhngY',
    appId: '1:828449012920:ios:b12db3d4009e595aeb484d',
    messagingSenderId: '828449012920',
    projectId: 'miprueba-55284',
    databaseURL: 'https://miprueba-55284-default-rtdb.firebaseio.com',
    storageBucket: 'miprueba-55284.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXTe-_OWgUqo29ZU6xScCdndBLkF95EvM',
    appId: '1:828449012920:web:01856c98faca91feeb484d',
    messagingSenderId: '828449012920',
    projectId: 'miprueba-55284',
    authDomain: 'miprueba-55284.firebaseapp.com',
    databaseURL: 'https://miprueba-55284-default-rtdb.firebaseio.com',
    storageBucket: 'miprueba-55284.firebasestorage.app',
    measurementId: 'G-23RRE1B7KL',
  );
}
